ALTER TABLE `admin` CHANGE `admin_id` `id` INT(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `course` CHANGE `course_id` `id` INT(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `instructor` CHANGE `instructor_id` `id` INT(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `student` CHANGE `student_id` `id` INT(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `track` CHANGE `track_id` `id` INT(11) NOT NULL AUTO_INCREMENT;